# Generated by Django 5.1.2 on 2025-12-20 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE_USER', 'Created User'), ('UPDATE_USER', 'Updated User'), ('DELETE_USER', 'Deleted User'), ('CHANGE_ROLE', 'Changed User Role'), ('RESET_PASSWORD', 'Reset User Password'), ('APPROVE_RESET', 'Approved Password Reset'), ('REJECT_RESET', 'Rejected Password Reset'), ('ACTIVATE_USER', 'Activated User'), ('DEACTIVATE_USER', 'Deactivated User'), ('CREATE_TASK', 'Created Task'), ('UPDATE_TASK', 'Updated Task'), ('DELETE_TASK', 'Deleted Task'), ('LOGIN', 'Admin Login'), ('LOGOUT', 'Admin Logout'), ('OTHER', 'Other Action')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='admin_activ_admin_u_769f24_idx'), models.Index(fields=['action'], name='admin_activ_action_a7d641_idx'), models.Index(fields=['target_user'], name='admin_activ_target__946f7d_idx'), models.Index(fields=['-created_at'], name='admin_activ_created_05e410_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Password Reset Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for request', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_password_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='password_re_token_625fe7_idx'), models.Index(fields=['status'], name='password_re_status_0e91d6_idx'), models.Index(fields=['user', 'status'], name='password_re_user_id_a8b61d_idx')],
            },
        ),
    ]
