# Generated by Django 5.1.2 on 2025-12-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Administrator Profile', 'verbose_name_plural': 'Administrator Profiles'},
        ),
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'verbose_name': 'Team Member Profile', 'verbose_name_plural': 'Team Member Profiles'},
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='can_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
    ]
