# Generated by Django 5.1.2 on 2025-12-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_adminprofile_options_and_more'),
        ('users', '0003_create_test_users'),
    ]

    operations = [
    ]
