# Generated by Django 5.1.2 on 2025-12-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_normalize_roles'),
        ('users', '0004_merge_20251211_1617'),
    ]

    operations = [
    ]
