# Generated by Django 5.1.2 on 2025-12-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task assigned'), ('TASK_STARTED', 'Task started'), ('TASK_DONE', 'Task completed'), ('TASK_REMINDER', 'Task reminder'), ('TASK_COMMENTED', 'Task commented')], max_length=20),
        ),
    ]
